name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.5

      - name: Install Python dependencies
        run: pip install black flake8
        
      - name: Lint Action
        uses: wearerequired/lint-action@v1.9.0
        with:
          flake8: true
